version: "3.10"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test_mcp
    command: 
    env_file:
      - .env
    ports:
      - "${MCP_PORT}:80"
    volumes:
      - .:/app
    environment:
      - MCP_HOST=${MCP_HOST}
      - MCP_PORT=${MCP_PORT}

    networks:
      - test_mcp_default

networks:
  test_mcp_default:
    driver: bridge
